# Day 11: NumPy 入门 —— 习题

> 请独立完成以下 10 题，完成后将答案发给我批改。
> 建议用时：60-90 分钟

## Easy

**1. 数组创建与基础属性**

用 `np.arange` 创建一个包含 0~99（含）的数组，然后：
- 将其 reshape 为形状 `(10, 10)`
- 打印形状、维度数、元素总数、数据类型
- 取出第 3 行（索引 2）的所有元素
- 取出第 5 列（索引 4）的所有元素

In [6]:
# 你的代码
import numpy as np

nums = np.arange(100).reshape(10,10)

print(nums)
print(nums.shape)
print(nums.ndim)
print(nums.size)
print(nums.dtype)
print(nums[2,:])
print(nums[:,4])


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
(10, 10)
2
100
int64
[20 21 22 23 24 25 26 27 28 29]
[ 4 14 24 34 44 54 64 74 84 94]


**2. 向量化运算**

给定数组 `prices = np.array([120, 85, 200, 150, 90])`：
- 计算每个价格打 8 折后的价格
- 计算每个价格是否超过 100（返回布尔数组）
- 计算所有价格的平均值
- 找出最高价的索引

In [11]:
# 你的代码
prices = np.array([120, 85, 200, 150, 90])

print(prices * 0.8)
print(prices > 100)
print(np.mean(prices))
print(np.argmax(prices))

[ 96.  68. 160. 120.  72.]
[ True False  True  True False]
129.0
2


**3. 布尔索引筛选**

给定数组 `scores = np.array([78, 92, 55, 88, 60, 95, 70, 82])`：
- 筛选出所有 >= 80 的分数
- 筛选出所有在 [60, 80) 区间内的分数（含60不含80）
- 把所有 < 60 的分数替换为 60（原地修改）
- 计算替换后的平均分

In [84]:
# 你的代码
scores = np.array([78, 92, 55, 88, 60, 95, 70, 82])

print(scores[scores >= 80])
print(scores[(scores >= 60) & (scores < 80)])
scores[scores < 60] = 60
print(scores)
print(np.mean(scores))

[92 88 95 82]
[78 60 70]
[78 92 60 88 60 95 70 82]
78.125


## Medium

**4. 二维数组与 axis**

给定一个 5×4 的数组，模拟 5 名学生 4 门课的成绩：
```python
grades = np.array([
    [85, 90, 78, 92],
    [76, 88, 90, 85],
    [92, 95, 88, 96],
    [65, 70, 72, 68],
    [88, 85, 90, 87]
])
```
- 计算每名学生的平均分（axis=?）
- 计算每门课的平均分（axis=?）
- 找出每名学生的最高分对应的课程索引（提示：`argmax`）
- 找出平均分最高的学生索引

In [21]:
# 你的代码
grades = np.array([
    [85, 90, 78, 92],
    [76, 88, 90, 85],
    [92, 95, 88, 96],
    [65, 70, 72, 68],
    [88, 85, 90, 87]
])

print(grades.mean(axis=1))
print(grades.mean(axis=0))
print(grades.argmax(axis=1))
print(grades.mean(axis=1).argmax())

[86.25 84.75 92.75 68.75 87.5 ]
[81.2 85.6 83.6 85.6]
[3 2 3 2 2]
2


**5. 数组形状操作**

给定 `arr = np.arange(24)`：
- reshape 为 `(4, 6)`，打印结果
- 用 `-1` 自动计算，reshape 为 `(3, ?)`
- 提取最后 2 行、前 3 列的子数组
- 将这个子数组展平为一维（用 `flatten()` 或 `reshape(-1)`）
- 验证展平后的元素个数是否等于 2×3=6

In [31]:
# 你的代码
arr = np.arange(24)

print(arr.reshape(4, 6))
arr = arr.reshape(3, -1)
print(arr)
sub_arr = arr[-2: , :3]
print(sub_arr)
sub_arr = sub_arr.flatten()
print(sub_arr)
print(sub_arr.size)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 8  9 10]
 [16 17 18]]
[ 8  9 10 16 17 18]
6


**6. 统计计算 —— 收益率分析**

给定某股票 10 天的日收益率（%）：
```python
returns = np.array([1.2, -0.5, 0.8, -1.0, 2.5, 0.3, -0.2, 1.5, -0.8, 0.6])
```
- 计算平均日收益率
- 计算收益率的标准差（波动率）
- 计算累计收益率（提示：`cumsum`）
- 找出收益率最高和最低的日期索引
- 计算正收益天数占比（提示：布尔数组 `.mean()`）

In [40]:
# 你的代码
returns = np.array([1.2, -0.5, 0.8, -1.0, 2.5, 0.3, -0.2, 1.5, -0.8, 0.6])

print(np.mean(returns))
print(np.std(returns))
print(np.cumsum(returns))
print(np.argmax(returns))
print(np.argmin(returns))
print(np.mean(returns[returns > 0]))
print(returns[returns > 0].mean())

0.43999999999999995
1.049952379872535
[1.2 0.7 1.5 0.5 3.  3.3 3.1 4.6 3.8 4.4]
4
3
1.15
1.15


参考答案

问题: 题目问的是「正收益天数占比」= 正收益天数 / 总天数，不是「正收益的平均收益率」。

In [85]:
# 方法1：布尔数组的 mean 就是 True 的比例
print((returns > 0).mean())  # 0.6（6天正收益 / 10天）

# 方法2：显式计数
print(np.sum(returns > 0) / len(returns))  # 0.6

0.6
0.6


**7. 条件替换与复合筛选**

给定数组 `data = np.array([15, 8, 22, 3, 18, 9, 30, 12, 5, 25])`：
- 创建一个新数组，规则：>20 的变为 '高'，<10 的变为 '低'，其余变为 '中'
  （提示：先创建字符串数组 `np.full_like`，或用 `np.where` 嵌套）
- 统计 '高'、'中'、'低' 各有多少个
- 用布尔索引找出所有 >10 且是偶数的元素

In [50]:
# 你的代码
data = np.array([15, 8, 22, 3, 18, 9, 30, 12, 5, 25])

str_data = np.full_like(data, '中', dtype=str)
str_data[np.where(data < 10)] = '低'
str_data[np.where(data > 20)] = '高'
print(str_data)
print(str_data[str_data == '高'].size)
print(str_data[str_data == '中'].size)
print(str_data[str_data == '低'].size)
print(data[(data > 10) & (data % 2 == 0)])

['中' '低' '高' '低' '中' '低' '高' '中' '低' '高']
3
3
4
[22 18 30 12]


## Hard

**8. 矩阵运算 —— 投资组合权重**

给定 3 只股票 × 5 天的收益率矩阵（行=股票，列=天数）：
```python
returns_matrix = np.array([
    [0.01,  0.02, -0.01,  0.015,  0.005],   # 股票A
    [0.005, 0.01,  0.02, -0.005,  0.01 ],   # 股票B
    [0.02, -0.01,  0.01,  0.02,  -0.005]    # 股票C
])
weights = np.array([0.5, 0.3, 0.2])  # 投资权重
```
- 计算每只股票 5 天的平均收益率（axis=?）
- 用**广播**计算：每天的投资组合收益率 = 当天3只股票的收益率 × 权重后求和
  （提示：`returns_matrix * weights.reshape(3,1)` 或直接用广播）
- 计算投资组合 5 天的平均收益率和波动率（标准差）
- 找出投资组合收益最高的是第几天

In [88]:
# 你的代码
returns_matrix = np.array([
    [0.01,  0.02, -0.01,  0.015,  0.005],   # 股票A
    [0.005, 0.01,  0.02, -0.005,  0.01 ],   # 股票B
    [0.02, -0.01,  0.01,  0.02,  -0.005]    # 股票C
])
weights = np.array([0.5, 0.3, 0.2])  # 投资权重

print(returns_matrix.mean(axis=1))
portfolio = returns_matrix * weights.reshape(3, 1)
print(portfolio.sum(axis=0, keepdims=True))
print(np.mean(portfolio))
print(np.std(portfolio))
print(portfolio.sum(axis=0, keepdims=True).argmax())

[0.008 0.008 0.007]
[[0.0105 0.011  0.003  0.01   0.0045]]
0.0026000000000000003
0.003746998799039039
1


参考答案

问题: portfolio 是加权后的 3×5 矩阵，但「投资组合收益率」应该是每天一个值（3只股票当天收益按权重加权求和），是一个长度为 5 的一维数组。

你算 np.mean(portfolio) 得到的是 15 个元素的平均，不是「投资组合 5 天的平均收益率」。

In [86]:
# 每天的投资组合收益率（一维数组，长度=5）
daily_portfolio = (returns_matrix * weights.reshape(3, 1)).sum(axis=0)
# 或: daily_portfolio = (returns_matrix.T @ weights)  # 矩阵乘法写法

print(daily_portfolio)  # [0.0105 0.011  0.003  0.01   0.0045]

# 投资组合的平均收益率和波动率
print(daily_portfolio.mean())   # 0.0078
print(daily_portfolio.std())    # 0.00344

# 收益最高的是第几天
print(daily_portfolio.argmax())  # 1（第2天，索引从0开始）

[0.0105 0.011  0.003  0.01   0.0045]
0.0078
0.003355592347112504
1


**9. 广播机制深入 —— 数据标准化**

给定 4×3 的数据矩阵（4个样本，3个特征）：
```python
features = np.array([
    [10, 200,  5],
    [20, 150, 10],
    [15, 180,  8],
    [25, 220, 12]
])
```
对每列做**Z-score标准化**：`z = (x - 列均值) / 列标准差`
- 计算每列的均值和标准差（用 axis，保持维度用于广播）
- 用广播实现标准化，结果应为 4×3 矩阵
- 验证标准化后每列的均值是否≈0、标准差是否≈1（浮点误差允许 1e-10 级别）

In [67]:
# 你的代码
features = np.array([
    [10, 200,  5],
    [20, 150, 10],
    [15, 180,  8],
    [25, 220, 12]
])

ft_mean = features.mean(axis=0)
ft_std = features.std(axis=0)
standarded_ft = (features - ft_mean)/ft_std
print(standarded_ft)

eps = 1e-10
mean_ok = np.all(np.abs(ft_mean) < eps)
std_ok = np.all(np.abs(ft_std - 1) < eps)
print(mean_ok)
print(std_ok)

[[-1.34164079  0.48336824 -1.45010473]
 [ 0.4472136  -1.45010473  0.48336824]
 [-0.4472136  -0.29002095 -0.29002095]
 [ 1.34164079  1.25675744  1.25675744]]
False
False


参考答案


问题: 你验证的是 ft_mean 和 ft_std（原始数据的均值和标准差），但标准化后的数据均值本来就不是 0！你验证错了对象。

应该验证的是 standarded_ft（标准化后的矩阵）的列均值和列标准差。

In [89]:
# 验证标准化后的数据
z_mean = standarded_ft.mean(axis=0)
z_std = standarded_ft.std(axis=0)

eps = 1e-10
mean_ok = np.all(np.abs(z_mean) < eps)      # ✅ 标准化后的均值≈0
std_ok = np.all(np.abs(z_std - 1) < eps)    # ✅ 标准化后的标准差≈1
print(mean_ok, std_ok)  # True True

True True


**10. 综合题 —— 用 NumPy 做销售数据分析**

给定某门店 7 天 × 3 个品类 的销售额矩阵（单位：元）：
```python
sales = np.array([
    [1200,  800,  600],   # 周一
    [1500,  900,  750],   # 周二
    [1100,  850,  500],   # 周三
    [1800, 1000,  900],   # 周四
    [2000, 1200, 1100],   # 周五
    [2500, 1500, 1300],   # 周六
    [2200, 1300, 1000]    # 周日
])
categories = ['食品', '饮料', '日用品']
```
请完成：
1. 计算每天的总销售额（3个品类之和）
2. 计算每个品类的周总销售额和日均销售额
3. 找出销售额最高的一天和对应的总额
4. 计算周末（周六、周日）的平均日总销售额 vs 工作日（周一~周五）的平均日总销售额
5. 找出「食品」品类中，哪几天的销售额超过了该品类周均值
6. **边界测试**: 在 cell 末尾列出你验证过的至少 3 个边界/特殊情况（如空数组、全0、负数等），并说明你的代码是否能正确处理

In [ ]:
# 你的代码
sales = np.array([
    [1200,  800,  600],   # 周一
    [1500,  900,  750],   # 周二
    [1100,  850,  500],   # 周三
    [1800, 1000,  900],   # 周四
    [2000, 1200, 1100],   # 周五
    [2500, 1500, 1300],   # 周六
    [2200, 1300, 1000],   # 周日
])
categories = ['食品', '饮料', '日用品']

print(sales.sum(axis=1))
print(sales.sum(axis=0))
print(sales.mean(axis=0))
print(sales.sum(axis=1).argmax())
print(sales[5,:].sum())
print(sales[-2:, :].sum(axis=1).mean())
print(sales[:5, :].sum(axis=1).mean())
food = sales[:, 0]
print(np.where(food > food.mean()))
# 如何系统的进行边界测试，请你教我一下

[2600 3150 2450 3700 4300 5300 4500]
[12300  7550  6150]
[1757.14285714 1078.57142857  878.57142857]
5
5300
4900.0
3240.0
(array([3, 4, 5, 6]),)


参考答案

In [90]:
# 边界测试清单
test_cases = [
    ("空数组", np.array([]), "sum返回0，mean会报Warning/返回nan，需特殊处理"),
    ("全0数组", np.zeros((3,3)), "均值=0，标准差=0，Z-score会除零报错"),
    ("含负数", np.array([-10, 0, 10]), "向量化、布尔索引、统计函数都正常"),
    ("单元素", np.array([[5]]), "std返回0（或nan，取决于ddof）"),
]

for name, arr, expected in test_cases:
    print(f"\n【{name}】")
    print(f"  数据: {arr}")
    try:
        print(f"  sum: {arr.sum()}")
        print(f"  mean: {arr.mean()}")
        print(f"  std: {arr.std()}")
    except Exception as e:
        print(f"  异常: {e}")


【空数组】
  数据: []
  sum: 0.0
  mean: nan
  std: nan

【全0数组】
  数据: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
  sum: 0.0
  mean: 0.0
  std: 0.0

【含负数】
  数据: [-10   0  10]
  sum: 0
  mean: 0.0
  std: 8.16496580927726

【单元素】
  数据: [[5]]
  sum: 5
  mean: 5.0
  std: 0.0


C:\Users\69261\AppData\Local\Temp\ipykernel_17444\4111403377.py:14: RuntimeWarning: Mean of empty slice
  print(f"  mean: {arr.mean()}")
c:\Users\69261\anaconda3\Lib\site-packages\numpy\_core\_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
c:\Users\69261\anaconda3\Lib\site-packages\numpy\_core\_methods.py:219: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
c:\Users\69261\anaconda3\Lib\site-packages\numpy\_core\_methods.py:178: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
c:\Users\69261\anaconda3\Lib\site-packages\numpy\_core\_methods.py:211: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


关键边界教训:
空数组: np.array([]).mean() 返回 nan 并报警告，不是报错。代码里如果后续用这个值做除法会出 nan 污染。

全0数组做 Z-score: std=0 导致除零，会得到 inf 或 nan。实际工程中要加判断 if std > 0。

单元素数组: std() 默认 ddof=0 返回 0；如果 ddof=1 返回 nan（因为分母为0）。
